/* ============================================================================
   data.js — static reference data for Fuelcast.
   Meal/snack library nutrition figures are compiled from published
   high-protein / weight-gain meal guides (see README "Sources"), rounded to
   practical serving sizes. No network calls, no AI: everything here ships
   with the app and is matched to the user by the rule-based scorer in calc.js.
   ========================================================================== */

const FC_DATA = (function () {
  'use strict';

  /* Tag vocabulary used by the recommender + the diet filter:
     high-protein | low-calorie | calorie-dense | vegetarian | vegan
     low-carb | quick | no-cook | post-workout                         */

  const MEALS = [
    /* ---------------------------------------------------------- breakfast */
    { id: 'b1', slot: 'breakfast', name: 'Greek Yogurt Protein Bowl', kcal: 350, protein: 34, carbs: 38, fat: 6, minutes: 5,
      items: '1 cup nonfat Greek yogurt, ½ cup berries, ¼ cup granola, 1 tsp honey',
      tags: ['high-protein', 'vegetarian', 'quick', 'no-cook'] },
    { id: 'b2', slot: 'breakfast', name: 'Protein Overnight Oats', kcal: 350, protein: 30, carbs: 45, fat: 8, minutes: 5,
      items: '½ cup rolled oats, 1 cup unsweetened almond milk, 1 scoop vanilla whey, 1 tbsp chia, ½ banana',
      tags: ['high-protein', 'vegetarian', 'quick', 'no-cook'] },
    { id: 'b3', slot: 'breakfast', name: 'Veggie Egg-White Scramble + Toast', kcal: 330, protein: 30, carbs: 30, fat: 9, minutes: 10,
      items: '5 egg whites + 1 whole egg, spinach, peppers, 1 slice whole-grain toast',
      tags: ['high-protein', 'low-calorie', 'vegetarian', 'quick'] },
    { id: 'b4', slot: 'breakfast', name: 'Crispy Breakfast Quesadilla', kcal: 427, protein: 44, carbs: 38, fat: 11, minutes: 12,
      items: 'Whole-wheat tortilla, 3 eggs, sliced turkey, low-fat cheese, salsa',
      tags: ['high-protein'] },
    { id: 'b5', slot: 'breakfast', name: 'Cottage Cheese & Berry Toast', kcal: 310, protein: 28, carbs: 36, fat: 5, minutes: 5,
      items: '2 slices whole-grain toast, ¾ cup low-fat cottage cheese, berries, cinnamon',
      tags: ['high-protein', 'vegetarian', 'quick', 'no-cook'] },
    { id: 'b6', slot: 'breakfast', name: 'Smoked Salmon Bagel Thin', kcal: 380, protein: 28, carbs: 40, fat: 12, minutes: 5,
      items: 'Bagel thin, 3 oz smoked salmon, 2 tbsp whipped cream cheese, capers, red onion',
      tags: ['high-protein', 'quick', 'no-cook'] },
    { id: 'b7', slot: 'breakfast', name: 'Banana Peanut-Butter Protein Smoothie', kcal: 520, protein: 40, carbs: 55, fat: 16, minutes: 5,
      items: '1 cup whole milk, 1 scoop whey, 1 banana, 2 tbsp peanut butter, ¼ cup oats',
      tags: ['high-protein', 'calorie-dense', 'vegetarian', 'quick', 'post-workout'] },
    { id: 'b8', slot: 'breakfast', name: 'Savory Oats with Egg', kcal: 430, protein: 24, carbs: 52, fat: 14, minutes: 12,
      items: '½ cup oats cooked in broth, 1 fried egg, parmesan, scallion, chili crisp',
      tags: ['vegetarian'] },
    { id: 'b9', slot: 'breakfast', name: 'Tofu Scramble Burrito', kcal: 450, protein: 28, carbs: 48, fat: 16, minutes: 15,
      items: 'Whole-wheat tortilla, ½ block firm tofu, black beans, salsa, ¼ avocado',
      tags: ['high-protein', 'vegan', 'vegetarian'] },
    { id: 'b10', slot: 'breakfast', name: 'Steel-Cut Oats, Whey & Almond Butter', kcal: 610, protein: 38, carbs: 66, fat: 20, minutes: 20,
      items: '1 cup cooked steel-cut oats, 1 scoop whey, 2 tbsp almond butter, blueberries',
      tags: ['high-protein', 'calorie-dense', 'vegetarian'] },

    /* -------------------------------------------------------------- lunch */
    { id: 'l1', slot: 'lunch', name: 'Chicken & Quinoa Power Salad', kcal: 420, protein: 38, carbs: 34, fat: 14, minutes: 10,
      items: '4 oz rotisserie chicken, ⅓ cup Greek-yogurt Dijon dressing, celery, grapes, almonds, ½ cup quinoa, greens',
      tags: ['high-protein', 'quick'] },
    { id: 'l2', slot: 'lunch', name: 'Turkey & Avocado Wrap', kcal: 450, protein: 34, carbs: 42, fat: 16, minutes: 8,
      items: 'Whole-wheat wrap, 5 oz sliced turkey, ¼ avocado, lettuce, tomato, mustard',
      tags: ['high-protein', 'quick', 'no-cook'] },
    { id: 'l3', slot: 'lunch', name: 'Tuna Poke-Style Rice Bowl', kcal: 480, protein: 40, carbs: 52, fat: 11, minutes: 12,
      items: '5 oz tuna, ¾ cup rice, edamame, cucumber, seaweed, soy-sesame drizzle',
      tags: ['high-protein'] },
    { id: 'l4', slot: 'lunch', name: 'Lentil & Feta Grain Bowl', kcal: 430, protein: 22, carbs: 58, fat: 13, minutes: 15,
      items: '1 cup lentils, ½ cup farro, roasted vegetables, 1 oz feta, lemon-tahini',
      tags: ['vegetarian'] },
    { id: 'l5', slot: 'lunch', name: 'Chicken Burrito Bowl', kcal: 520, protein: 45, carbs: 55, fat: 12, minutes: 15,
      items: '5 oz grilled chicken, ¾ cup brown rice, black beans, pico, lettuce, salsa',
      tags: ['high-protein'] },
    { id: 'l6', slot: 'lunch', name: 'Shrimp Stir-Fry over Cauliflower Rice', kcal: 340, protein: 38, carbs: 22, fat: 10, minutes: 15,
      items: '6 oz shrimp, mixed vegetables, 1 tsp sesame oil, 1½ cups cauliflower rice',
      tags: ['high-protein', 'low-calorie', 'low-carb'] },
    { id: 'l7', slot: 'lunch', name: 'Big Cobb Salad, Light Vinaigrette', kcal: 460, protein: 40, carbs: 14, fat: 28, minutes: 12,
      items: '4 oz chicken, 2 eggs, 1 slice bacon, ½ oz blue cheese, greens, 1 tbsp vinaigrette',
      tags: ['high-protein', 'low-carb'] },
    { id: 'l8', slot: 'lunch', name: 'Chickpea & Tuna Mediterranean Salad', kcal: 400, protein: 32, carbs: 36, fat: 13, minutes: 8,
      items: '1 can tuna in water, ¾ cup chickpeas, cucumber, tomato, olives, olive oil, lemon',
      tags: ['high-protein', 'quick', 'no-cook'] },
    { id: 'l9', slot: 'lunch', name: 'Soba Noodles with Edamame & Peanut Sauce', kcal: 520, protein: 24, carbs: 68, fat: 18, minutes: 15,
      items: '2 oz soba, 1 cup edamame, shredded cabbage, carrot, 2 tbsp peanut sauce',
      tags: ['vegan', 'vegetarian'] },
    { id: 'l10', slot: 'lunch', name: 'Turkey Chili with Greek Yogurt', kcal: 430, protein: 36, carbs: 42, fat: 12, minutes: 5,
      items: '1½ cups lean turkey chili, dollop of nonfat Greek yogurt, scallion',
      tags: ['high-protein', 'quick'] },
    { id: 'l11', slot: 'lunch', name: 'Roast Beef & Swiss on Rye', kcal: 480, protein: 38, carbs: 46, fat: 15, minutes: 8,
      items: '2 slices rye, 5 oz roast beef, 1 slice Swiss, mustard, pickles, side of carrots',
      tags: ['high-protein', 'quick', 'no-cook'] },
    { id: 'l12', slot: 'lunch', name: 'Loaded Salmon Rice Bowl', kcal: 700, protein: 45, carbs: 70, fat: 26, minutes: 20,
      items: '6 oz salmon, 1 cup rice, ½ avocado, edamame, teriyaki glaze',
      tags: ['high-protein', 'calorie-dense'] },

    /* ------------------------------------------------------------- dinner */
    { id: 'd1', slot: 'dinner', name: 'Sesame-Ginger Glazed Chicken & Quinoa', kcal: 450, protein: 40, carbs: 38, fat: 14, minutes: 25,
      items: '5 oz chicken breast, 1 tsp sesame oil + soy + ginger + garlic + 1 tsp honey glaze, broccoli, ½ cup quinoa',
      tags: ['high-protein'] },
    { id: 'd2', slot: 'dinner', name: 'Baked Salmon, Sweet Potato & Asparagus', kcal: 520, protein: 38, carbs: 42, fat: 20, minutes: 30,
      items: '5 oz salmon, 1 medium sweet potato, asparagus, 1 tsp olive oil',
      tags: ['high-protein'] },
    { id: 'd3', slot: 'dinner', name: 'Turkey Meatballs & Zucchini Noodles', kcal: 380, protein: 40, carbs: 22, fat: 15, minutes: 30,
      items: '5 oz lean turkey meatballs, marinara, zucchini noodles, parmesan',
      tags: ['high-protein', 'low-calorie', 'low-carb'] },
    { id: 'd4', slot: 'dinner', name: 'Sheet-Pan Chicken Fajitas', kcal: 430, protein: 41, carbs: 36, fat: 13, minutes: 25,
      items: '5 oz chicken, peppers and onions, 2 corn tortillas, salsa, lime',
      tags: ['high-protein'] },
    { id: 'd5', slot: 'dinner', name: 'Lean Beef Stir-Fry with Brown Rice', kcal: 550, protein: 42, carbs: 52, fat: 17, minutes: 25,
      items: '5 oz sirloin, broccoli, snap peas, ¾ cup brown rice, garlic-soy',
      tags: ['high-protein'] },
    { id: 'd6', slot: 'dinner', name: 'Cod with Lemon Butter & Green Beans', kcal: 330, protein: 38, carbs: 14, fat: 13, minutes: 20,
      items: '6 oz cod, 1 tsp butter, lemon, green beans, small side salad',
      tags: ['high-protein', 'low-calorie', 'low-carb'] },
    { id: 'd7', slot: 'dinner', name: 'Black Bean & Sweet Potato Tacos', kcal: 460, protein: 18, carbs: 68, fat: 14, minutes: 25,
      items: '3 corn tortillas, 1 cup black beans, roasted sweet potato, slaw, avocado crema',
      tags: ['vegan', 'vegetarian'] },
    { id: 'd8', slot: 'dinner', name: 'Tofu Coconut Curry with Jasmine Rice', kcal: 560, protein: 26, carbs: 64, fat: 22, minutes: 30,
      items: '½ block firm tofu, light coconut curry, mixed vegetables, ¾ cup jasmine rice',
      tags: ['vegan', 'vegetarian', 'calorie-dense'] },
    { id: 'd9', slot: 'dinner', name: 'Lightened Chicken Parmesan & Salad', kcal: 520, protein: 48, carbs: 36, fat: 19, minutes: 25,
      items: '6 oz baked breaded chicken, marinara, part-skim mozzarella, side salad',
      tags: ['high-protein'] },
    { id: 'd10', slot: 'dinner', name: 'Shrimp Scampi over Whole-Wheat Linguine', kcal: 540, protein: 34, carbs: 62, fat: 17, minutes: 20,
      items: '6 oz shrimp, 2 oz whole-wheat linguine, garlic, 2 tsp olive oil, parsley, lemon',
      tags: ['high-protein'] },
    { id: 'd11', slot: 'dinner', name: 'Steak, Baked Potato & Broccoli', kcal: 680, protein: 50, carbs: 58, fat: 25, minutes: 35,
      items: '6 oz sirloin, 1 large baked potato, 1 tbsp sour cream, roasted broccoli',
      tags: ['high-protein', 'calorie-dense'] },
    { id: 'd12', slot: 'dinner', name: 'Protein-Boosted Chicken Alfredo Bake', kcal: 760, protein: 52, carbs: 70, fat: 28, minutes: 40,
      items: '6 oz chicken, 3 oz pasta, cottage-cheese alfredo, peas, parmesan',
      tags: ['high-protein', 'calorie-dense'] },

    /* -------------------------------------------------------------- snack */
    { id: 's1', slot: 'snack', name: 'Greek Yogurt + Almonds', kcal: 220, protein: 20, carbs: 14, fat: 9, minutes: 1,
      items: '¾ cup nonfat Greek yogurt, 12 almonds',
      tags: ['high-protein', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's2', slot: 'snack', name: 'Apple + Peanut Butter', kcal: 190, protein: 4, carbs: 28, fat: 8, minutes: 1,
      items: '1 apple, 1 tbsp peanut butter',
      tags: ['vegan', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's3', slot: 'snack', name: 'Protein Shake (water)', kcal: 130, protein: 25, carbs: 4, fat: 2, minutes: 1,
      items: '1 scoop whey isolate, 12 oz water, ice',
      tags: ['high-protein', 'low-calorie', 'low-carb', 'vegetarian', 'quick', 'no-cook', 'post-workout'] },
    { id: 's4', slot: 'snack', name: 'Cottage Cheese + Pineapple', kcal: 180, protein: 22, carbs: 18, fat: 2, minutes: 1,
      items: '¾ cup low-fat cottage cheese, ½ cup pineapple',
      tags: ['high-protein', 'low-calorie', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's5', slot: 'snack', name: 'Beef Jerky + Clementine', kcal: 170, protein: 16, carbs: 18, fat: 2, minutes: 1,
      items: '1 oz beef jerky, 1 clementine',
      tags: ['high-protein', 'low-calorie', 'quick', 'no-cook'] },
    { id: 's6', slot: 'snack', name: 'Hummus + Veggie Sticks', kcal: 180, protein: 7, carbs: 20, fat: 9, minutes: 2,
      items: '¼ cup hummus, carrots, cucumber, bell pepper',
      tags: ['vegan', 'vegetarian', 'low-calorie', 'quick', 'no-cook'] },
    { id: 's7', slot: 'snack', name: 'Two Hard-Boiled Eggs', kcal: 155, protein: 13, carbs: 1, fat: 11, minutes: 1,
      items: '2 hard-boiled eggs, flaky salt, pepper',
      tags: ['high-protein', 'low-calorie', 'low-carb', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's8', slot: 'snack', name: 'Shelled Edamame', kcal: 190, protein: 18, carbs: 14, fat: 8, minutes: 3,
      items: '1 cup shelled edamame, sea salt',
      tags: ['high-protein', 'vegan', 'vegetarian', 'low-calorie', 'quick'] },
    { id: 's9', slot: 'snack', name: 'Turkey & Cheese Roll-Ups', kcal: 200, protein: 24, carbs: 2, fat: 11, minutes: 2,
      items: '4 slices turkey, 1 oz cheese, mustard',
      tags: ['high-protein', 'low-carb', 'low-calorie', 'quick', 'no-cook'] },
    { id: 's10', slot: 'snack', name: 'Trail Mix', kcal: 340, protein: 9, carbs: 28, fat: 22, minutes: 1,
      items: '¼ cup nuts, dried fruit and dark chocolate mix',
      tags: ['calorie-dense', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's11', slot: 'snack', name: 'Whole-Milk Protein Smoothie', kcal: 480, protein: 38, carbs: 48, fat: 14, minutes: 5,
      items: '1 cup whole milk, 1 scoop whey, banana, 1 tbsp honey, 1 tbsp chia',
      tags: ['high-protein', 'calorie-dense', 'vegetarian', 'quick', 'post-workout'] },
    { id: 's12', slot: 'snack', name: 'Peanut Butter Banana Toast', kcal: 330, protein: 10, carbs: 42, fat: 14, minutes: 3,
      items: '2 slices whole-grain toast, 1½ tbsp peanut butter, 1 banana',
      tags: ['calorie-dense', 'vegan', 'vegetarian', 'quick'] },
    { id: 's13', slot: 'snack', name: 'Chocolate Milk, 16 oz', kcal: 320, protein: 16, carbs: 52, fat: 8, minutes: 1,
      items: '16 oz low-fat chocolate milk',
      tags: ['calorie-dense', 'vegetarian', 'quick', 'no-cook', 'post-workout'] },
    { id: 's14', slot: 'snack', name: 'Rice Cakes + Cottage Cheese', kcal: 200, protein: 16, carbs: 26, fat: 3, minutes: 2,
      items: '2 rice cakes, ½ cup cottage cheese, everything seasoning',
      tags: ['high-protein', 'low-calorie', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's15', slot: 'snack', name: 'Granola & Whole-Milk Greek Yogurt', kcal: 450, protein: 24, carbs: 48, fat: 18, minutes: 2,
      items: '1 cup whole-milk Greek yogurt, ½ cup granola, honey',
      tags: ['high-protein', 'calorie-dense', 'vegetarian', 'quick', 'no-cook'] },
    { id: 's16', slot: 'snack', name: 'Dark Chocolate & Almonds', kcal: 210, protein: 5, carbs: 14, fat: 16, minutes: 1,
      items: '2 squares 85% dark chocolate, 15 almonds',
      tags: ['calorie-dense', 'vegan', 'vegetarian', 'quick', 'no-cook'] }
  ];

  /* MET values for the "close the gap with movement" coach. kcal/min = MET*3.5*kg/200 */
  const ACTIVITIES = [
    { id: 'walk',     name: 'Brisk walk',        met: 4.3 },
    { id: 'jog',      name: 'Easy jog',          met: 8.0 },
    { id: 'bike',     name: 'Cycling, moderate', met: 7.0 },
    { id: 'strength', name: 'Strength training', met: 5.0 },
    { id: 'swim',     name: 'Swimming laps',     met: 7.0 },
    { id: 'hiit',     name: 'HIIT circuit',      met: 9.0 },
    { id: 'yoga',     name: 'Yoga / mobility',   met: 3.0 },
    { id: 'elliptical', name: 'Elliptical',      met: 5.5 }
  ];

  const DIET_FILTERS = [
    { id: 'all',         label: 'No filter',     test: () => true },
    { id: 'vegetarian',  label: 'Vegetarian',    test: m => m.tags.includes('vegetarian') },
    { id: 'vegan',       label: 'Vegan',         test: m => m.tags.includes('vegan') },
    { id: 'low-carb',    label: 'Lower carb',    test: m => m.tags.includes('low-carb') },
    { id: 'quick',       label: '10 min or less', test: m => m.minutes <= 10 }
  ];

  return { MEALS, ACTIVITIES, DIET_FILTERS };
})();
